### PR TITLE
add python client code(PetStore)

### PR DESCRIPTION
**Pull request by msyyc**

### CODE REVIEW

**Comment by lirenhe** [comment]
Please include the following sample file and code in the PR. thanks
samples.py or samples/sample.py


```
from petstore import PetStoreClient
client = PetStoreClient()
pet = client.pets.get(1)

assert pet.name == "Kiwi"
```

**Comment by tadelesh** [comment]
> Please include the following sample file and code in the PR. thanks samples.py or samples/sample.py
> 
> ```
> from petstore import PetStoreClient
> client = PetStoreClient()
> pet = client.pets.get(1)
> 
> assert pet.name == "Kiwi"
> ```

added. @msyyc i think this pr could be merged.

**Comment by msyyc** [comment]
@tadelesh @lirenhe Since this PR needs bump TCGC 0.48.5 for Python while other language emitter has not upgraded, so I will wait for other languages before merge.

**Comment by tadelesh** [comment]
> @tadelesh @lirenhe Since this PR needs bump TCGC 0.48.5 for Python while other language emitter has not upgraded, so I will wait for other languages before merge.

merged main and tcgc version is correct and regen is ok. we could merge it.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
